Title:			Chaotic set plotting
Author:			Dave Walker
Version:		
Title From:		Documentation
Author From:		Documentation
Version From:		Documentation
Supplier:		Dave Walker   WalkerDM@UK.AC.CARDIFF.MULTICS
Date:			14/01/87
Keywords:		
Shareware:		No
Machine:		BBC Micro
Operating system:	OS
Memory requirements:	
Peripherals needed:	
Other s/ware needed:	
Directory:		micros/bbc/a03
Date mounted/updated:	14/01/87
File names:		a03cha.bas           The program, in BASIC
			a03cha.doc           Documentation for the program
Unarchived files:	
Unarchived size:	
Omissions:		
See also:		

-------------------------------------------------------------------------------

Acquiring the package:

Download the file a03cha.bas using Kermit and then use *EXEC a03cha.bas to load
it into memory

Description:

The program and documentation give a basic introduction to chaotic sets and
have been developed after a lecture given at the 20th Anniversary Conference of
the British Computer Society in December of last year.

