/***********                */
/*   68HC11.H               */
/***********                */



#define PORTA   0x000
#define PIOC    0x002
#define PORTC   0x003
#define PORTB   0x004
#define PORTCL  0x005
#define DDRC    0x007
#define PORTD   0x008
#define DDRD    0x009
#define PORTE   0x00A
#define CFORC   0x00B
#define OC1M    0x00C
#define OC1D    0x00D
#define TCNT    0x00E
#define TIC1    0x010
#define TIC2    0x012
#define TIC3    0x014
#define TOC1    0x016
#define TOC2    0x018
#define TOC3    0x01A
#define TOC4    0x01C
#define TOC5    0x01E
#define TCTL1   0x020
#define TCTL2   0x021
#define TMSK1   0x022
#define TFLG1   0x023
#define TMSK2   0x024
#define TFLG2   0x025
#define PACTL   0x026
#define PACNT   0x027
#define SPCR    0x028
#define SPSR    0x029
#define SPDR    0x02A
#define BAUD    0x02B
#define SCCR1   0x02C
#define SCCR2   0x02D
#define SCSR    0x02E
#define SCDR    0x02F
#define ADCTL   0x030
#define ADR1    0x031
#define ADR2    0x032
#define ADR3    0x033
#define ADR4    0x034
#define OPTION  0x039
#define COPRST  0x03A
#define PPROG   0x03B
#define HPRIO   0x03C
#define INIT    0x03D
#define TEST1   0x03E
#define CONFIG  0x03F



